[log]
  level = "INFO"

[accessLog]

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[http.routers]
  [http.routers.http_catchall]
    entryPoints = ["web"]
    middlewares = ["https_redirect"]
    rule = "HostRegexp(`{any:.+}`)"
    service = "noop"

[http.services]
  # noop service, the URL will be never called
  [http.services.noop.loadBalancer]
    [[http.services.noop.loadBalancer.servers]]
      url = "http://0.0.0.0:0"

[http.middlewares]
  [http.middlewares.https_redirect.redirectScheme]
    scheme = "https"
    permanent = true

[api]
  dashboard = true


[providers.docker]
  watch = true
  exposedByDefault = false

[certificatesResolvers.le.acme]
  storage = "/data/acme.json"

  [certificatesResolvers.le.acme.httpChallenge]
    entryPoint = "web"

[metrics]
  [metrics.prometheus]
    addEntryPointsLabels = true
    addServicesLabels = true
    manualRouting = true
